name: 'servc spec test'
description: Tests a service library against the servc spec

inputs:
  dockerfile:
    description: 'The dockerfile location'
    required: false
    default: 'Dockerfile'
  context:
    description: 'The context to build'
    required: false
    default: '.'
  suite:
    description: 'The test suite to run'
    required: false
    default: ''
  version:
    description: 'The version of the servc spec to test against'
    required: false
    default: 'main'

runs:
  using: 'composite'

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: serv-c/docs
        ref: ${{ inputs.version }}
        path: servc-docs
        sparse-checkout: |
          tests
          requirements.test.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Test Build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: false
        tags: servc:latest

    - uses: actions/setup-python@v5

    - run: pip install -r requirements.test.txt
      shell: bash
      working-directory: servc-docs

    - name: Run tests
      shell: bash
      working-directory: servc-docs
      env:
        CACHE_URL: redis://redis
        BUS_URL: amqp://guest:guest@rabbitmq
      run: python -m unittest tests/${{ inputs.suite }}/**/*.py
