name: "Publish to Pages"
on:
  push:

permissions:
  contents: write

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install -r requirements.txt

      - if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force

      - run: mkdocs build
